In [1]:
import gym
import random
import numpy as np
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay = 0.001

In [5]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0, 1)
        
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = (1-learning_rate)*q_table[state,action]+learning_rate*(reward+discount_rate*np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay*episode)
   
    rewards_all_episodes.append(rewards_current_episode)

In [6]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("")    
print(q_table)

1000 :  0.04000000000000003
2000 :  0.21100000000000016
3000 :  0.4230000000000003
4000 :  0.5310000000000004
5000 :  0.6270000000000004
6000 :  0.6600000000000005
7000 :  0.6400000000000005
8000 :  0.6860000000000005
9000 :  0.6540000000000005
10000 :  0.6700000000000005

[[0.53933409 0.47768779 0.47163037 0.45218914]
 [0.31973883 0.27753649 0.21707504 0.44743745]
 [0.38496767 0.27577947 0.27122407 0.27482119]
 [0.10498364 0.16341107 0.06714762 0.07582081]
 [0.55329398 0.34034197 0.36464657 0.3597223 ]
 [0.         0.         0.         0.        ]
 [0.15807229 0.07251597 0.29619382 0.06442493]
 [0.         0.         0.         0.        ]
 [0.30502214 0.28594997 0.31824214 0.60711786]
 [0.41782567 0.67901518 0.25632995 0.5072187 ]
 [0.69405092 0.3220854  0.43300622 0.2815679 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53359904 0.56673994 0.76856458 0.52572017]
 [0.73433084 0.9048738  0.70992915 0.72269469]
 [0.         0.      

In [7]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*******EPISODE ", episode+1, "*******\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            
            if reward == 1:
                print("You reached your goal!")
                time.sleep(3)
            else:
                print("You reached a hole!")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()        

  (Down)
SFFF
FHFH
FFFH
HFFG
You reached your goal!
